// Session summary card: the LLM-distilled recap of what happened in the
// session (summary paragraph + key events + timeline beats), persisted by
// content-service. Timeline entries and events are click-to-seek into the
// recording player, mirroring the transcript viewer. Entity names that
// resolve to campaign wiki pages (drafted by this very session or already
// present) render as clickable links.

"use client";

import Link from "next/link";
import { Badge, Button, Card, EmptyState, fmtPercent } from "@/components/ui";
import { LinkedText, normalizeName, type LinkIndex } from "@/components/linked-text";
import type { SessionSummary } from "@/lib/api";

function parseTimeToSeconds(time: string): number | null {
  const parts = time.split(":").map((p) => Number(p));
  if (parts.some((n) => Number.isNaN(n))) return null;
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  return null;
}

/** A chip whose label links to its wiki page when one exists in the index. */
function LinkedChip({
  name,
  campaignId,
  index,
  className,
}: {
  name: string;
  campaignId?: string;
  index?: LinkIndex | null;
  className: string;
}) {
  const target = campaignId && index ? index.byName.get(normalizeName(name)) : undefined;
  if (!target) return <span className={className}>{name}</span>;
  return (
    <Link href={`/campaigns/${campaignId}/pages/${target.id}`} className={`${className} hover:underline`}>
      {name}
    </Link>
  );
}

export function SessionSummaryCard({
  summary,
  onSeek,
  onRegenerate,
  regenerating,
  campaignId,
  linkIndex,
  currentPromptVersion,
}: {
  summary: SessionSummary | null;
  /** Jump the recording player to a timestamp (seconds) — used by timeline rows. */
  onSeek?: (seconds: number) => void;
  /** DEBUG (developer accounts): re-run wiki generation from the same transcript. */
  onRegenerate?: () => void;
  regenerating?: boolean;
  /** Campaign the session belongs to: entity names link to its wiki pages. */
  campaignId?: string;
  /** Campaign page index: known entity names become links. */
  linkIndex?: LinkIndex | null;
  /** Prompt version the deployment currently uses (from /api/content/llm):
   *  the badge tracks prompt evolution instead of the version frozen on the
   *  last generation. */
  currentPromptVersion?: string | null;
}) {
  const debugButton = onRegenerate ? (
    <Button
      variant="ghost"
      onClick={onRegenerate}
      disabled={regenerating}
      title="Re-run wiki generation from the same transcription"
    >
      {regenerating ? "Re-running…" : "Debug: rerun generation"}
    </Button>
  ) : null;

  if (!summary || !summary.summary) {
    return (
      <Card>
        <div className="flex flex-wrap items-center justify-between gap-2">
          <h2 className="text-lg font-semibold">Session summary</h2>
          {debugButton}
        </div>
        <div className="mt-4">
          <EmptyState>
            The AI summary appears here once the transcript has been distilled —
            it usually shows up when the wiki generation finishes.
          </EmptyState>
        </div>
      </Card>
    );
  }

  const hasEvents = (summary.events?.length ?? 0) > 0;
  const hasTimeline = (summary.timeline_entries?.length ?? 0) > 0;
  const hasCharacters = (summary.characters?.length ?? 0) > 0;
  const hasLocations = (summary.locations?.length ?? 0) > 0;

  // The badge shows the prompt version the deployment uses NOW; when the
  // summary was generated by an older prompt, that version is called out too.
  const storedVersion = summary.prompt_version;
  const promptBadge = currentPromptVersion ? (
    <span
      title={
        storedVersion && storedVersion !== currentPromptVersion
          ? `generated with ${storedVersion}`
          : undefined
      }
    >
      <Badge tone="slate">
        prompt {currentPromptVersion}
        {storedVersion && storedVersion !== currentPromptVersion ? ` · made with ${storedVersion}` : ""}
      </Badge>
    </span>
  ) : storedVersion ? (
    <Badge tone="slate">prompt {storedVersion}</Badge>
  ) : null;

  return (
    <Card>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
        <h2 className="text-lg font-semibold">Session summary</h2>
        <div className="flex flex-wrap items-center gap-2 text-xs">
          {summary.llm_provider && summary.llm_model ? (
            <Badge tone="slate">
              {summary.llm_provider} / {summary.llm_model.replace(/^.*\//, "")}
            </Badge>
          ) : null}
          {summary.confidence !== null && summary.confidence !== undefined ? (
            <Badge tone="green">confidence {fmtPercent(summary.confidence)}</Badge>
          ) : null}
          {promptBadge}
          {debugButton}
        </div>
      </div>

      <p className="text-sm leading-relaxed text-slate-200">
        <LinkedText text={summary.summary} campaignId={campaignId} index={linkIndex} />
      </p>

      {hasTimeline ? (
        <div className="mt-5">
          <h3 className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">
            Key moments
          </h3>
          <ul className="space-y-1.5">
            {summary.timeline_entries.map((entry, i) => {
              const seconds = parseTimeToSeconds(entry.time);
              return (
                <li key={i}>
                  <div className="group flex w-full items-start gap-3 rounded-lg px-2 py-1.5 text-left transition hover:bg-slate-800/60">
                    {seconds !== null && onSeek ? (
                      <button
                        onClick={() => onSeek(seconds)}
                        title="Jump to this moment in the recording"
                        className="mt-0.5 shrink-0 font-mono text-xs text-slate-500 tabular-nums hover:text-ember-400"
                      >
                        {entry.time}
                      </button>
                    ) : (
                      <span className="mt-0.5 shrink-0 font-mono text-xs text-slate-500 tabular-nums">
                        {entry.time}
                      </span>
                    )}
                    <span className="text-sm leading-relaxed text-slate-200">
                      <LinkedText text={entry.summary} campaignId={campaignId} index={linkIndex} />
                    </span>
                  </div>
                </li>
              );
            })}
          </ul>
        </div>
      ) : null}

      {hasEvents ? (
        <div className="mt-5">
          <h3 className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">
            Important events
          </h3>
          <ul className="space-y-3">
            {summary.events.map((event, i) => (
              <li key={i} className="rounded-lg border border-slate-800 bg-slate-800/30 px-3 py-2.5">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="text-sm font-semibold text-slate-100">
                    <LinkedText text={event.title} campaignId={campaignId} index={linkIndex} />
                  </span>
                  {event.confidence !== null && event.confidence !== undefined ? (
                    <Badge tone="green">{fmtPercent(event.confidence)}</Badge>
                  ) : null}
                </div>
                {event.description ? (
                  <p className="mt-1 text-sm leading-relaxed text-slate-300">
                    <LinkedText text={event.description} campaignId={campaignId} index={linkIndex} />
                  </p>
                ) : null}
                {event.participants?.length ? (
                  <div className="mt-1.5 flex flex-wrap gap-1.5">
                    {event.participants.map((p) => (
                      <LinkedChip
                        key={p}
                        name={p}
                        campaignId={campaignId}
                        index={linkIndex}
                        className="rounded-full bg-slate-700/50 px-2 py-0.5 text-xs text-slate-300"
                      />
                    ))}
                  </div>
                ) : null}
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {hasCharacters || hasLocations ? (
        <div className="mt-5 flex flex-wrap gap-6">
          {hasCharacters ? (
            <div>
              <h3 className="mb-1.5 text-xs font-bold uppercase tracking-wider text-slate-500">Characters</h3>
              <div className="flex flex-wrap gap-1.5">
                {summary.characters.map((c) => (
                  <LinkedChip
                    key={c.name}
                    name={c.name}
                    campaignId={campaignId}
                    index={linkIndex}
                    className="rounded-full bg-blue-500/10 px-2 py-0.5 text-xs text-blue-300"
                  />
                ))}
              </div>
            </div>
          ) : null}
          {hasLocations ? (
            <div>
              <h3 className="mb-1.5 text-xs font-bold uppercase tracking-wider text-slate-500">Locations</h3>
              <div className="flex flex-wrap gap-1.5">
                {summary.locations.map((l) => (
                  <LinkedChip
                    key={l.name}
                    name={l.name}
                    campaignId={campaignId}
                    index={linkIndex}
                    className="rounded-full bg-amber-500/10 px-2 py-0.5 text-xs text-amber-300"
                  />
                ))}
              </div>
            </div>
          ) : null}
        </div>
      ) : null}
    </Card>
  );
}
